---
title: "COVID-19 qPCR Analysis"
output: html_document
---

```{r initialize}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyr)
library(ggplot2)
library(readxl)
library(stringr)
```

# R Markdown

```{r Read Data}

#Hello! The only inputs you need to enter are in lines 24, 25, 26, and 431

#qpcr_data is your raw data from the quant6
#cid_sheet is your key containing sample IDs and the IDs you entered into the machine

qpcr_data <- read_excel("/Users/English/Desktop/03-23_002COVID192.xls", sheet='Results', skip=40)
qpcr_data2 <- read_excel("/Users/English/Desktop/03-23_002COVID192.xls")
cid_sheet <- read_excel("/Users/English/Desktop/key.xlsx")
cid <- data.frame(cid_sheet)

run_ID <- 'CReM_qPCR'
inst_num <- qpcr_data2[32,2]
date <- qpcr_data2[24,2]

```

```{r result format}
# 1 – specimen identifier (CID# or Accession #), this must be a BMC identifier
# 2 – well # or id (optional)
# 3 – test code
# 4 – test result (numeric or text interpretation)
# 5 – method/device (if more than one analyzer exists) [available in Sunquest SRT type 50 transaction]
# 6 – instrument result data/time stamp (optional) [available in Sunquest SRT type 50 transaction]
# 7 – CR LF (carriage return and line feed)
```


# Formatting the Data

```{r Format Data}

qpcr_data$CT <- gsub("Undetermined", "45", qpcr_data$CT)
qpcr_data$CT <- as.numeric(qpcr_data$CT)

qpcr_data$testID <- run_ID
qpcr_data$instrument <- inst_num[,1]$`384-Well Block`
qpcr_data$date <- date$`384-Well Block`


N1 <- qpcr_data %>% filter(`Target Name` == 'N1')
N2 <- qpcr_data %>% filter(`Target Name` == 'N2')
RP <- qpcr_data %>% filter(`Target Name` == 'RP')

```

```{r Split}

N1 <- qpcr_data %>% filter(`Target Name` == 'N1')
N2 <- qpcr_data %>% filter(`Target Name` == 'N2')
RP <- qpcr_data %>% filter(`Target Name` == 'RP')

```

# QC
```{r QC}
#Look for inconsistent results

N1 <- N1 %>% arrange(`Sample Name`)
N2 <- N2 %>% arrange(`Sample Name`)
RP <- RP %>% arrange(`Sample Name`)

N1Res <- function(N1){
    sapply(N1$CT, function(x) if(x <= 40) "1" else if (x > 39) "0")
}

N1$Result <- as.numeric(N1Res(N1))
N2$Result <- as.numeric(N1Res(N2))
RP$Result <- as.numeric(N1Res(RP))

N1$Consistency = 0
N2$Consistency = 0
RP$Consistency = 0

for (i in 1:nrow(N1)) {
  if (i %% 2 == 0) {
    if (N1[i,]$Result == N1[i-1,]$Result) {
      N1[i,]$Consistency = 1
      N1[i-1,]$Consistency = 1
    }
  }
}

for (i in 1:nrow(N2)) {
  if (i %% 2 == 0) {
    if (N2[i,]$Result == N2[i-1,]$Result) {
      N2[i,]$Consistency = 1
      N2[i-1,]$Consistency = 1
    }
  }
}

for (i in 1:nrow(RP)) {
  if (i %% 2 == 0) {
    if (RP[i,]$Result == RP[i-1,]$Result) {
      RP[i,]$Consistency = 1
      RP[i-1,]$Consistency = 1
    }
  }
}

N1$N1Res = 1
N2$N2Res = 1
RP$RPRes = 1


# Merge N1, N2
# if they're both inconsistent, keep
# if one is, other isn't change consistencies to 1

test2 <- data.frame(N1$Consistency, N2$Consistency)

#for (i in 1:nrow(test2)) {
#  if (test2[i,]$N1.Consistency == 1 & test2[i,]$N2.Consistency == 1) {
#    N1[i,]$Consistency = 1
#    N2[i,]$Consistency = 1
#  }
#  else if(test2[i,]$N1.Consistency == 1 & test2[i,]$N2.Consistency == 0) {
#    N1[i,]$Consistency = 1
#    N2[i,]$Consistency = 1
#  }
#  else if(test2[i,]$N1.Consistency == 0 & test2[i,]$N2.Consistency == 1) {
#    N1[i,]$Consistency = 1
#    N2[i,]$Consistency = 1
#  }
#  else if(test2[i,]$N1.Consistency == 0 & test2[i,]$N2.Consistency == 0) {
#    N1[i,]$Consistency = 0
#    N2[i,]$Consistency = 1
#  }
#}

for (i in 1:nrow(N1)) {
  if (N1[i,]$Result == 1 & N1[i,]$Consistency == 1) {
    N1[i,]$N1Res = 1
  }
  else if(N1[i,]$Result == 0 & N1[i,]$Consistency == 1) {
    N1[i,]$N1Res = 0
  }
  else if(N1[i,]$Consistency == 0) {
    N1[i,]$N1Res = 2
  }
}

for (i in 1:nrow(N2)) {
  if (N2[i,]$Result == 1 & N2[i,]$Consistency == 1) {
    N2[i,]$N2Res = 1
  }
  else if(N2[i,]$Result == 0 & N2[i,]$Consistency == 1) {
    N2[i,]$N2Res = 0
  }
  else if(N2[i,]$Consistency == 0) {
    N2[i,]$N2Res = 2
  }
}

for (i in 1:nrow(RP)) {
  if (RP[i,]$Result == 1 & RP[i,]$Consistency == 1) {
    RP[i,]$RPRes = 1
  }
  else if(RP[i,]$Result == 0 & RP[i,]$Consistency == 1) {
    RP[i,]$RPRes = 0
  }
  else if(RP[i,]$Consistency == 0) {
    RP[i,]$RPRes = 2
  }
}

N1Results <- data.frame(N1$`Sample Name`, N1$Well, N1$testID, N1$N1Res, N1$instrument, N1$date, N1$`Ct Mean`)
N1Results$SampleName <- N1Results$N1..Sample.Name.
N1Results <- distinct(N1Results, SampleName, .keep_all=TRUE)
rownames(N1Results) <- N1Results$SampleName
N2Results <- data.frame(N2$`Sample Name`, N2$Well, N2$testID, N2$N2Res, N2$instrument, N2$date, N2$`Ct Mean`)
N2Results$SampleName <- N2Results$N2..Sample.Name.
N2Results <- distinct(N2Results, SampleName, .keep_all=TRUE)
rownames(N2Results) <- N2Results$SampleName
RPResults <- data.frame(RP$`Sample Name`, RP$Well, RP$testID, RP$RPRes, RP$instrument, RP$date, RP$`Ct Mean`)
RPResults$SampleName <- RPResults$RP..Sample.Name.
RPResults <- distinct(RPResults, SampleName, .keep_all=TRUE)
rownames(RPResults) <- RPResults$SampleName



Final <- merge(N1Results, N2Results, by = 'SampleName')

Final2 <- merge(Final, RPResults, by = 'SampleName')

#Final Logic
  #If N1, N2 = 1, Positive
  #If N1 = 0, N2 = 1 or N1 = 1, N2 = 0, Inconclusive
  #If N1 = 0, N2 = 0, RP = 1, Negative
  #If N1 = 2 or N2 = 2, Invalid (Bad technical replicates)
  #If N1 = 0, N2 = 0, RP = 0 or 2, Invalid

Final2$FinalResult = 'FIX'



```

```{r finalresults}

for (i in 1:nrow(Final2)) {
  if (Final2[i,]$N1.N1Res == 1 & Final2[i,]$N2.N2Res == 1) {
    Final2[i,]$FinalResult = 'POSITIVE'
  }
  else if(Final2[i,]$N1.N1Res == 1 & Final2[i,]$N2.N2Res == 0)  {
    Final2[i,]$FinalResult = 'POSITIVE'
  }
  else if(Final2[i,]$N1.N1Res == 0 & Final2[i,]$N2.N2Res == 1)  {
    Final2[i,]$FinalResult = 'POSITIVE'
  }
  else if(Final2[i,]$N1.N1Res == 0 & Final2[i,]$N2.N2Res == 0 & Final2[i,]$RP.RPRes == 1)  {
    Final2[i,]$FinalResult = 'NEGATIVE'
  }
  else if(Final2[i,]$N1.N1Res == 0 & Final2[i,]$N2.N2Res == 0 & Final2[i,]$RP.RPRes == 0)  {
    Final2[i,]$FinalResult = 'INVALID'
  }
  else if(Final2[i,]$N1.N1Res == 2 & Final2[i,]$N2.N2Res == 2)  {
    Final2[i,]$FinalResult = 'INCONCLUSIVE'
  }
  else if(Final2[i,]$N1.N1Res == 2 & Final2[i,]$N2.N2Res == 1)  {
    Final2[i,]$FinalResult = 'POSITIVE'
  }
  else if(Final2[i,]$N1.N1Res == 1 & Final2[i,]$N2.N2Res == 2)  {
    Final2[i,]$FinalResult = 'POSITIVE'
  }
  else if(Final2[i,]$N1.N1Res == 2 & Final2[i,]$N2.N2Res == 0)  {
    Final2[i,]$FinalResult = 'INCONCLUSIVE'
  }
  else if(Final2[i,]$N1.N1Res == 0 & Final2[i,]$N2.N2Res == 2)  {
    Final2[i,]$FinalResult = 'INCONCLUSIVE'
  }
  else if(Final2[i,]$N1.N1Res == 0 & Final2[i,]$N2.N2Res == 0 & Final2[i,]$RP.RPRes == 2)  {
    Final2[i,]$FinalResult = 'INCONCLUSIVE'
  }
}

```

# Results

### Positive

```{r Positive}

for (i in 1:nrow(Final2)) {
  if (Final2[i,]$FinalResult == 'POSITIVE') {
    print(as.character(Final2[i,]$SampleName), quote=FALSE)
  }
}

```

### Negative

```{r Negative}

for (i in 1:nrow(Final2)) {
  if (Final2[i,]$FinalResult == 'NEGATIVE') {
    print(as.character(Final2[i,]$SampleName), quote=FALSE)
  }
}

```

### Inconclusive (N1 and N2 are inconsistent)

```{r Inconclusive}

for (i in 1:nrow(Final2)) {
  if (Final2[i,]$FinalResult == 'INCONCLUSIVE') {
    print(as.character(Final2[i,]$SampleName), quote=FALSE)
  }
}

```

### Inconclusive (Technical replicates are inconsistent)

```{r Inconclusive TechRep}

for (i in 1:nrow(Final2)) {
  if (Final2[i,]$FinalResult == 'INCONCLUSIVE') {
    print(as.character(Final2[i,]$SampleName), quote=FALSE)
  }
}

```

### Invalid

```{r Invalid}

for (i in 1:nrow(Final2)) {
  if (Final2[i,]$FinalResult == 'INVALID') {
    print(as.character(Final2[i,]$SampleName), quote=FALSE)
  }
}

```

```{r format it}

N1Results$final <- Final2$FinalResult
N1Results$N1.N1Res <- N1Results$final

names(N1Results)[names(N1Results) == "N1..Sample.Name."] <- "Sample"
names(N1Results)[names(N1Results) == "N1.Well"] <- "Well"
names(N1Results)[names(N1Results) == "N1.testID"] <- "TestID"
names(N1Results)[names(N1Results) == "N1.N1Res"] <- "Result"
names(N1Results)[names(N1Results) == "N1.instrument"] <- "Instrument"
names(N1Results)[names(N1Results) == "N1.date"] <- "Date"
N1Results$N2_Mean <- N2Results$N2..Ct.Mean.
N1Results$RP_Mean <- RPResults$RP..Ct.Mean.


drop <- c("SampleName","final")
drop2 <- c("SampleName","final", "N1..Ct.Mean.", "N2_Mean", "RP_Mean")
sunquest_format = N1Results[,!(names(N1Results) %in% drop)]

sunquest_format2 = N1Results[,!(names(N1Results) %in% drop2)]
sunquest_format3 = sunquest_format2




`%notin%` <- Negate(`%in%`)

for (i in 1:nrow(sunquest_format2)) {
  if (sunquest_format2[i,]$Result == 'INCONCLUSIVE') {
    if (grepl(as.character('_R'), as.character(sunquest_format2[i,]$Sample))) {
      sunquest_format2[i,]$Result = 'INCONCLUSIVE'
    }
    else {
      sunquest_format2[i,]$Result = 'REMOVE'
    }
  }
}

for (i in 1:nrow(sunquest_format2)) {
  if (sunquest_format2[i,]$Result == 'INVALID') {
    if (grepl(as.character('_R'), as.character(sunquest_format2[i,]$Sample))) {
      sunquest_format2[i,]$Result = 'INVALID'
    }
    else {
      sunquest_format2[i,]$Result = 'REMOVE'
    }
  }
}

drop2 <- "CID"
cid_attach <- merge(sunquest_format2, cid, by.x="Sample", by.y="CREM_ID")
bmc <- cid_attach

test24 <- merge(sunquest_format3, cid, by.x="Sample", by.y="CREM_ID")


bmc$Sample <- bmc$CID


bmc <- bmc[,!names(bmc) %in% drop2]

bmc <- bmc[-grep("NTC", bmc$Sample),]
bmc <- bmc[-grep(as.character("Control"), as.character(bmc$Sample)),]

test24 <- test24[-grep("NTC", test24$Sample),]
test24 <- test24[-grep(as.character("Control"), as.character(test24$CID)),]

summary <- test24

bmc <- bmc[!grepl("REMOVE", bmc$Result),]



#write.csv(sunquest_format, file="/Users/English/Desktop/testcrem.csv", quote=FALSE, row.names = FALSE)

#sunquest_format <- sunquest_format[!grepl("REMOVE", sunquest_format$Result),]

```

```{r write file}

time <- Sys.time()
year <- substr(time, 1, 4)
month <- substr(time, 6, 7)
day <- substr(time, 9, 10)
time2 <- substr(time, 12, 20)

hour <- substr(time, 12, 13)
min <- substr(time, 15, 16)
sec <- substr(time, 18, 19)

filename <- paste("Quan6flex_",  month, day, year, "_", hour, min, sec, sep="")

write.csv(bmc, file=paste("/Users/English/Desktop/", filename, ".csv", sep=""), quote=FALSE, row.names = FALSE, eol="\n")

write.csv(sunquest_format, file=paste("/Users/English/Desktop/", filename, "_CREM", ".csv", sep=""), quote=FALSE, row.names = FALSE, eol="\n")

```



```{r summary stats}
total_tests <- nrow(summary)
positive <- sum(str_count(summary$Result, 'POSITIVE'))
negative <- sum(str_count(summary$Result, 'NEGATIVE'))
inconclusive <- sum(str_count(summary$Result, 'INCONCLUSIVE'))
invalid <- sum(str_count(summary$Result, 'INVALID'))


sumstats <- data.frame("Total" = total_tests, "Positive" = positive, "Negative" = negative, "Inconclusive" = inconclusive, "Invalid" = invalid)

#this is your output file
write.csv(sumstats, file=paste("/Users/English/Desktop/", filename, "_summary", ".csv", sep=""), quote=FALSE, row.names = FALSE, eol="\n")


```

